[2023-02-18 05:04:25,321] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_1 2023-02-17T00:00:00+00:00 [queued]>
[2023-02-18 05:04:27,209] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_1 2023-02-17T00:00:00+00:00 [queued]>
[2023-02-18 05:04:27,254] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-02-18 05:04:27,308] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2023-02-18 05:04:27,309] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-02-18 05:04:28,477] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): runme_1> on 2023-02-17T00:00:00+00:00
[2023-02-18 05:04:28,985] {standard_task_runner.py:52} INFO - Started process 2945 to run task
[2023-02-18 05:04:33,973] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'runme_1', '2023-02-17T00:00:00+00:00', '--job-id', '3191', '--pool', 'default_pool', '--raw', '--subdir', '/home/airflow/.local/lib/python3.6/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpmutvf7la', '--error-file', '/tmp/tmpnld9zub1']
[2023-02-18 05:04:35,649] {standard_task_runner.py:77} INFO - Job 3191: Subtask runme_1
[2023-02-18 05:04:50,192] {logging_mixin.py:104} INFO - Running <TaskInstance: example_bash_operator.runme_1 2023-02-17T00:00:00+00:00 [running]> on host a39de0034eff
[2023-02-18 05:05:06,990] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=runme_1
AIRFLOW_CTX_EXECUTION_DATE=2023-02-17T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-17T00:00:00+00:00
[2023-02-18 05:05:08,096] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2023-02-18 05:05:09,451] {bash.py:158} INFO - Running command: echo "example_bash_operator__runme_1__20230217" && sleep 1
[2023-02-18 05:05:11,509] {bash.py:169} INFO - Output:
[2023-02-18 05:05:18,452] {bash.py:173} INFO - example_bash_operator__runme_1__20230217
[2023-02-18 05:05:20,340] {bash.py:177} INFO - Command exited with return code 0
[2023-02-18 05:05:31,124] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=runme_1, execution_date=20230217T000000, start_date=20230218T050425, end_date=20230218T050531
[2023-02-18 05:05:39,693] {local_task_job.py:188} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-02-18 05:05:39,696] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 2945
[2023-02-18 05:06:31,353] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-02-18 05:06:31,354] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2023-02-18 05:06:31,685] {process_utils.py:66} INFO - Process psutil.Process(pid=2945, status='terminated', exitcode=1, started='05:04:28') (2945) terminated with exit code 1
